---
- name: Watch for new and modified files on Windows
  hosts: localhost
  sources:
    # - community.eda.file_watch: #watchdog:
    #     path: C:\Users\Administrator\Downloads
    #     recursive: true
    #     patterns:
    #       - "*.txt"

    - name: File Monitor
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /test

  rules:
    - name: New file created
      condition: event.payload.event_type == 'created'
      action:
        run_job_template:
          name: "Windows File Audit - Created"
          organization: "Default"
          job_args:
            extra_vars:
              # Map the source payload to a variable named 'eda_payload'
              eda_payload: "{{ ansible_eda.events.payload }}"

    - name: File modified
      condition: event.payload.event_type == 'modified'
      action:
        run_job_template:
          name: "Windows File Audit - Modified"
          organization: "Default"
          job_args:
            extra_vars:
              # Map the source payload to a variable named 'eda_payload'
              eda_payload: "{{ ansible_eda.events.payload }}"